### ISSUE TITLE
Back button is broken

### ISSUE THREAD

**Issue by sandersonet** [aptible/diesel.aptible.com#95] opened 2015-02-17 21:24 UTC
If you navigate away from Stack#show and then click the back button, you are not returned to Stack#show.

**Comment by bantic** [comment] 2015-02-24 16:01
I am seeing this behavior again on master (as of 585a3d3258c0b20ca431bb8bfd5a747affc4810c).

Example of broken behavior:

   * visit /stacks/:id/apps
   * click an app -> /apps/:app_id/services
   * click back button -> same page (/apps/:app_id/services)

Confirmed in Chrome and FF

**Comment by bantic** [comment] 2015-03-16 17:27
The above comment no longer breaks for me, but this is another broken case:

  * visit /stacks/:id/apps
  * click on an app that has never been deployed ( -> /apps/:app_id/deploy)
  * click back button -> ends up on same page

**Comment by mixonic** [comment] 2015-03-16 22:18
Right. After diving into this, we determined the issue is resolved in Ember 1.11 (it seems to have been a bug in 1.10).

#155 updates us to Ember 1.11. Closing this.

**Closed by mixonic** 2015-03-16 22:18 UTC
Labels: bug
